development:
  sqs_pdf_conversion_queue_name: document_conversion_queue_vlad
  ddb_one_word_reverse_index_table_name: one_word_reverse_index
  stop_word_file: config/stop_words.txt
  s3_bucket_name: thenotist
  output_html_prefix: test_html_store
  output_css_prefix: test_css_store
  output_pdf_prefix: test_pdf_store
  output_thumb_prefix: test_thumb_store

test:
  sqs_pdf_conversion_queue_name: test_document_conversion_queue
  ddb_one_word_reverse_index_table_name: one_word_reverse_index
  stop_word_file: config/stop_words.txt
  s3_bucket_name: thenotist
  output_html_prefix: test_html_store
  output_css_prefix: test_css_store
  output_pdf_prefix: test_pdf_store
  output_thumb_prefix: test_thumb_store

production:
  sqs_pdf_conversion_queue_name: document_conversion_queue_prod
  ddb_one_word_reverse_index_table_name: one_word_reverse_index
  stop_word_file: config/stop_words.txt
  s3_bucket_name: thenotist
  output_html_prefix: html_store
  output_css_prefix: css_store
  output_pdf_prefix: pdf_store
  output_thumb_prefix: thumb_store
